### ISSUE TITLE
Image editing tab redesign (menu)

### ISSUE THREAD

**Issue by rimutaka** [mVentory/MVentory_Productivity#12]
See related issue #13

Image editing menu requires theme modifications and does not always work out of the box.

It will be easier if we move the thumbs and image editing menus to the productivity panel at the top.

Image editing menu in action: https://www.marqueed.com/collections/164900/images/764471/

Required layout: https://www.marqueed.com/collections/164900/images/764472/

Separation between Upload and Edit tabs: https://www.marqueed.com/collections/164900/images/764474/

1. Remove the image editing menu from the thumbs in the theme

2. Display all images + image editing menu on hover inside Upload tab

**Comment by anatolykazantsev** [comment]
Merged. Done
