### ISSUE TITLE
Image editing tab redesign (tabs)

### ISSUE THREAD

**Issue by rimutaka** [mVentory/MVentory_Productivity#13]
See related issue https://github.com/mVentory/MVentory_Productivity/issues/12

Image editing menu requires theme modifications and does not always work out of the box.

It will be easier if we move the thumbs and image editing menus to the productivity panel at the top.

Image editing menu in action: https://www.marqueed.com/collections/164900/images/764471/

Required layout: https://www.marqueed.com/collections/164900/images/764472/

Separation between Upload and Edit tabs: https://www.marqueed.com/collections/164900/images/764474/

1. Hardcode white b/g, black text, basic buttons in the text editing panel to avoid colors being inherited from the theme. We had too many problems with themes conflicting with this basic layout.

2. Do not show Upload and Edit tabs at the same time

**Comment by anatolykazantsev** [comment]
Done and merged
