### ISSUE TITLE
Does not work With Redis

### ISSUE THREAD

**Issue by liquidia** [mVentory/MVentory_Productivity#18]
Tool bar does not show up if you are using redis for session/ back-end cache.

**Comment by rimutaka** [comment]
Can you provide more info?

**Comment by liquidia** [comment]
Not sure if its redis but i found another mistake created group name "Reviewers" as mentioned on the magneto connect plugin detail page instead of "Reviewer" please fix this typo on magneto connect.

I will test it again with redis tomorrow and will confirm if there is a redis issue or not.

Thanks

**Comment by anatolykazantsev** [comment]
Yes, we don't support configuration where redis is used to store sessions. Because we "manually" load admin session data to check if current user is logged as admin
