### ISSUE TITLE
Error Installing this

### ISSUE THREAD

**Issue by Samuelseggs** [mVentory/MVentory_Productivity#30]
I got this error "MVentory_Productivity" requires module "MVentory_API" 
Reference site : eshopng.net
Magento : 1.9.2.2

Thanks

**Comment by rimutaka** [comment]
@Samuelseggs , MVentory_API is available from Magento Connect here https://www.magentocommerce.com/magento-connect/mobile-pos-inventory-barcode-scanning-photos-and-more-on-android.html
